### PR TITLE
Make urdfdom_headers-config.cmake relocatable

### PR DESCRIPTION
**Pull request by seanyen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Interesting! Usually conda has a mechanism to detect the prefix (which is a really really long string with lots of "placeholder_placeholder..." In it (you might have seen this?). Upon package creation this is replaced with "anaconda1anaconda2anaconda3", and then for the installation the actual prefix is inserted (as far as I understand). 

Just out of curiosity did this not work here?

**Comment by seanyen** [comment]
I bet you are talking about `has_prefix_files`. Yes, I tried it yesterday, however it never works for me. I was digging into `conda-build` but I haven't yet confirmed if it is a `conda-build` limitation:
(However, the logic looks suspicious to me.)
https://github.com/conda/conda-build/blob/master/conda_build/build.py#L240-L250

**Comment by wolfv** [comment]
Hi Sean, 

thanks for pointing me to these lines in conda-build. I agree with you, they look like they could be the culprit.
Catkin is right now making it's way to the conda repositories. I am working on cpp_common next. 

Btw for the naming scheme, we're going to go with `ros-`-prefix everything, and then replace underscores with dashes (so that e.g. `cpp_common` will be named `ros-cpp-common` on conda), which is similar to how the deb packages are named. (Only thing we still need to think about is `ros-ros-environment` and these kind of names, I would rather remove the first `ros-` here (but keep it for `ros-rosmsg` etc).

I hope the following packages will go rather quickly. 

Indeed I am "using" superflore for the generation of the recipes, but it's a huge mess that I am a little hesitant to share with the world :)
Making a clean superflore (or conda-skeleton) implementation would definitely be nice.
You can find the current state of the recipe generation here: https://github.com/wolfv/superflore/tree/add_conda/superflore/generators/conda (please don't judge me by the quality of the code ;)

I am not sure if superflore is the best tool for the job because as far as I understand it also makes a few assumptions about the git layout of the recipes etc. I am just using it in a hacky way to generate recipes in the `recipes/` subdirectory.

Cheers!

**Pull request merged**
